### PR TITLE
invalid login message functionality

### LINKED ISSUE #67: implement functionality for invalid login attempts
## intro
HI @pranavsant ! in this sprint, **you'll implement functionality to handle incorrect login attempts on the cloud app**. our cloud app login currently has no indication that you entered the incorrect email or password.

https://github.com/user-attachments/assets/301226ec-82e6-49d4-9513-d0ad38122c9c

## steps
when a user enters the wrong email or password, show a visible error message and animate the form to show the error. also, when a login request is in progress, briefly disable the login button (so users can't repeatedly spam the button).

### part 1: understand and refactor our existing functionality
look at our apps/cloud/actions/login.ts file to see how we currently handle our login. make sure to understand the error object that we return upon an invalid login attempt.

- [ ] create a new file: `apps/cloud/app/login/LoginForm.tsx`. most of your work will be in this file.
- [ ] move the login form (email/password label & input, submit button, etc.) out of `apps/cloud/app/(auth)/login/page.tsx` into our new file. then, in `apps/cloud/app/(auth)/login/page.tsx`, import LoginForm and use that instead.

### part 2: implement login and error functionality in LoginForm file
- [ ] add [states](https://react.dev/learn/managing-state) for `email`, `password`, `errorMessage`, and `isSubmitting`.
- [ ] convert the inputs to [controlled inputs](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable). this should make it so that if the user edits the fields after an invalid attempt, the error message will go away. 
- [ ] call `loginWithEmailPassword` and set `isSubmitting` to true. if the result returned is an error, show the failed-login UI.

### part 3: add in UX changes
- [ ] at the top of the [submit handler](https://www.geeksforgeeks.org/reactjs/react-onsubmit-event/), if `isSubmitting` is true, return early to prevent duplicate submissions. also, look into [preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault).
- [ ] while the request is running, disable the submit button. add styling to lower the opacity.
- [ ] render `errorMessage` to "Incorrect email or password." Render that message above the submit button (below the password input).

- use [event handlers!!](https://www.w3schools.com/js/js_events.asp).
- **reach out to @Emilypeng1104 to understand how/where she did the styling!!**

## goals
this sprint should be done in three main files:
```
modified: apps/cloud/app/login/page.tsx
modified: (the login styling files that emily made)
new file: apps/cloud/app/login/LoginForm.tsx
```

### PR DESCRIPTION
**Pull request by pranavsant**
[//]: # "add the issue number from your sprint in the space below"
closes #67

### description / changes made 
[//]: # "list (in bullet points) the main changes of this PR, especially if it's something that wasn't mentioned in the original issue."

- Better functionality for logging in
- Displays error message in red when the password or email is incorrect
- Submit button becomes greyed out and tells user that submission is happening when clicked
- File structure changed, form moved into new LoginForm.tsx component

### screenshots / demo vids
[//]: # "show evidence that your PR works -- especially important if this PR changed the UI."

Screenshot 2026-03-16 at 7 53 42 AM
Screenshot 2026-03-16 at 7 54 47 AM

### notes
[//]: # "is there anything else that the reviewer of this PR should know? is there anything you'd like feedback on?"

CC: @nathandtam

### CODE REVIEW

File: apps/cloud/app/(auth)/components/LoginForm.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
+import * as style from "../components/style";
```
Comment (nathandtam) [inline apps/cloud/app/(auth)/components/LoginForm.tsx]: loginform needs to become interactive by becoming a client component

add "use client"

Comment (nathandtam) [inline apps/cloud/app/(auth)/components/LoginForm.tsx]: also, import useState and store some states

**Review by nathandtam — COMMENTED** [review]
right now you moved the form into a separate component, but the form still works exactly like before because it still submits through action={loginAction} and has no client-side state

for this sprint, the login form component needs to be a client component with useState, controlled inputs, and an onSubmit handler so it can show loading and error feedback

check the linked resources from #67 , there will be links to more info within the issue text

**Comment by pranavsant** [comment]
I made the changes for all the comments. Should be good now.
